### PR TITLE
use python matrix with travis, switch to pytest in tox, fix license check

### PR DESCRIPTION
**Pull request by aabadie**
For testing integration between tox and travis matrix.

### CODE REVIEW

**Comment by aabadie** [comment]
I added rules for testing against python 2.7, 3.4, 3.5 and 3.6. There's a coverage module in pytest : tox now uses it and results are published on codecov.io
Look much better now.

Code coverage can still be improved (only 55% right now)

**Comment by cladmi** [comment]
You should also run `lint` on all python versions. Valid syntax in python3.5 can be invalid in python2.7.

**Comment by aabadie** [comment]
> You should also run lint on all python versions. Valid syntax in python3.5 can be invalid in python2.7

That's a matter of taste. Python 2.7 is only here for backward compatibility and will be dropped in a couple of years (and maybe sooner)

**Comment by aabadie** [comment]
> You should also run lint on all python versions

@cladmi, I opened #13 ;)

**Pull request merged**
