### PR TITLE
get experiment nodes list when you don't specify nodes list parser option

### PR DESCRIPTION
**Pull request by fsaintma**
By default when you don't specify nodes_list or exclude_nodes_list parser option you get
an empty nodes list for the command.
Modify the behaviour of the parser for executing the command on all experiment nodes when you don't specify parser option. (-l grenoble,a8,4 or -e grenoble,a8,4)

### CODE REVIEW

**Comment by aabadie** [comment]
Looks good. It raises an error with flake8:
https://travis-ci.org/iot-lab/ssh-cli-tools/builds/197266977#L432

Is there a corresponding public method in iotlabcli tools ?

**Comment by fsaintma** [comment]
No we have just a public method which give the experiment nodes list without list structure. We get a JSON with items list of experiment nodes. So we must parse the JSON and get the network_address attribute for each nodes. The private method in iotlabcli/common do this job.
So two solutions : I copy the code of the private method in ssh_cli_tools or we must do a pull request in cli_tools repo to modify the scope of the private function.
Which solution  you prefer ?

**Comment by aabadie** [comment]
> Which solution you prefer ?

You can import the private function and call it directly. Then flake8 seems happy (tox returned no error locally).
I allowed myself to push a commit in your branch.

**Comment by fsaintma** [comment]
best solution :)
we merge the pull request ?
ps : which merge pull request you prefer (merge commit or rebase and merge, ...) ?

**Comment by aabadie** [comment]
squash and merge if it can be squashed in a single commit (this is the case here) or ask the contributor to squash in meaningful commits and then merge

**Comment by cladmi** [comment]
It would be a better idea to also make this function public in the cli-tools (and maybe keep the private one for some time).
As it's private, it implies it could be removed, or the api changed without notice.
I should have made a public one sooner.

To be robust, a 'call the new public one or the private one' could help managing old and new versions too.

**Comment by aabadie** [comment]
> It would be a better idea to also make this function public in the cli-tools (and maybe keep the private one for some time).

btw, ssh-cli-tools is still in beta and so it's not a big deal. we could also add a rules to use a version of iotlab-cli <= current version (2.3 ?) to avoid version mismatch.

Otherwise +1 for the public method.

**Comment by cladmi** [comment]
You should not restrict it to an old cli-tools version as both will be installed with last versions on the frontends.
Its more being compatible with last version to work on the frontend, and a maybe also with old version for the users computers.

**Pull request merged**
